# Supabase Configuration
supabase.url=https://snzttzweuedajiiipmjh.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuenR0endldWVkYWppaWlwbWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzNTA2MTIsImV4cCI6MjA5NjkyNjYxMn0.nI2sFfopwSBwJVyiCPXnp13xNUFgnED_dERuQdc7kq8
