# Supabase Configuration
supabase.url=https://snzttzweuedajiiipmjh.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuenR0endldWVkYWppaWlwbWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzNTA2MTIsImV4cCI6MjA5NjkyNjYxMn0.nI2sFfopwSBwJVyiCPXnp13xNUFgnED_dERuQdc7kq8
resend.api.key=re_Q99vHWxv_6CDutyenuhTWpY6aNw89FVKs
resend.from.email=onboarding@resend.dev
server.mode=local
server.local.ip=localhost
server.hosted.ip=your-hosted-server-ip-or-domain.com

# Gmail SMTP Configuration (Optional: Bypass domain verification)
gmail.username=
gmail.password=
